language: ruby
rvm:
- 2.0.0
script:
- bundle install
- bundle exec rake
env:
  global:
  - TEST_AWS_REGION=us-west-1
  - secure: "eCJlzOosNYRjry6YB4kDi9aae1XKHRWVpUU0Qd0XfKD8Dj4nxnkcZNm1tF3LwfMGEru19RVBFvoN00DXngHbh4SXt0hxukWtlyKHQzyrlDpWoTNE5Gta8eOXx+QpJUC8bOfSoRan2L3c3YHNzQkL/mky9PBtT3fIo+3R3h+go5s="
  - secure: "JbJ3ac+dee1yeyw3RI6GfJmMSSdKGk4QGkihZnIVnn5l/0X/6Cr7YTUFTiQV3wu1tDDpDsGBffnjnZ+eZHNAqHrJFlFF4HPfQ622Od19aMOmPc46lFXWMOxbqXx8/q+os90YnC+hC6U4BIZDR2ZFkHzr9WaiocspukT0z6VGNA0="
