language: ruby
rvm:
- 2.0.0
script:
- bundle install
- bundle exec rake
env:
  global:
  - TEST_AWS_REGION=us-west-1
  - secure: "HS5unmXeingv7Kw577GRAInsORGc6Mw8G5FlUi55IxgxpzXNaUN1hPqNpNKB6HsO5A1dCi2Fvl+8ULYvKbFAfo8dGMTdGyl7MGaQ6L0DjdUzrgwAU448XdhBAhq8jzoZ2hMdjIviE4WHmAasBB8kaUE8+wNYALjCwmtea79PcFg="
  - secure: "BqIJqpooZpqLKuiZnVYpNxC42E7yJFhYkkdE+MFlJCN7qjt24h2QHV/sG87nWTV8mL5WeDl0HSWdvw3KHqX73xyP0w0zKItMX1hW4TZIK6tzL2WF7r4EOP70yJLRaG6/bmzoeFSXywOpK9McyG/H6eeRnLnjffI7BNRBC9u5Naw="
  - TEST_INTERVAL=3
