language: ruby
rvm:
- 2.0.0
script:
- bundle install
- bundle exec rake
env:
  global:
  - TEST_AWS_REGION=us-west-1
  - secure: "ZV1HJ+opn2e9hH6jd0xR2uAwzrlHXhWdWL8qqOnZrd1cDhWFOjrhnT7X0bjz1VPpwaADm3fhsJnZ2sMAqdxDnfJ6joA+75avSe+6vITl862WdkQ38jnupicWZSShF14Hxm+owHqPfN2Gd9EivHKXUrMH6K18e9gwU2FW7/Wzleg="
  - secure: "J+651erOW7JGPVG+rWRsXGZvv8p8GLfdMiCAwZkVPttA0XGgf/bMFG2TrsvwHE4oYo0QXGM1huKdBOrxj9OLkcWkafYVHMtEBYdb3GLrvuS3Kb4tNItw9goQCv2C+Bw5W9MGjIVB6XxCUpNS0W3YWNKRlM2LZ4DMPju7ZyAWD6Q="
