language: ruby
rvm:
- 2.0.0
script:
- bundle install
- bundle exec rake
env:
  global:
  - TEST_AWS_REGION=us-west-1
  - secure: "BW8qIC7075WzXfQQD21NcDyU7qKB55IyZq8b87lCdwXBVobY/eEgKXH0WziaQRrynHcTfpmJwLiJ2n/sOy9gCkVfsZZaoDJZe7bdrcpJZ/qLu3xf6qLQ+aer++KjVrZS1sMR2XwkM0dnGLxcPq/OfdU9n13xD8UnNfF4eWD/kRc="
  - secure: "s5/h+hIGlhPND2NYUef7sJmZvZgAOBVBj+ysXNxw5KbxFZn35wjjq8cfp6IZ1OaN4eTzWWenLJ4bxLZ2uiUpRrOcvo0MGCg/SMhe3Hml4TJGsNKq6Fdm7HfPGrvEyAK3QjK4zHWFySPKBiX71W65ARyWhKHVtX7JtwlhL73cjzQ="
  - TEST_INTERVAL=3
