language: ruby
rvm:
- 2.0.0
script:
- bundle install
- bundle exec rake
env:
  global:
  - TEST_AWS_REGION=us-west-1
  - secure: "JGa42SE/DDMT5zfl61Sq06h31Lre7UB7bxhX+Cta23UPRUUcYC+6kiEphPumnf3kJza+uylHMZj5AWrVXlTg2QsSH7ObZhMsbtKUvzsZB06azqzm4LGTcFePZ3zpgDa08EEjV4xJBre3pFtBw/AuJIvx1Hu9I5hYdDVEn8i5RVQ="
  - secure: "G6yL4kAd07SI6cd9D/ZyFqQh50hXCRZS+8G6tVfyQTOxw7KA5eQWqpxvRTLWVJe7e7rNl9O74EHa8cNAeDJKGWxw6bsZ7Ar65xpTr5juRxN5UiQ7wquRF7opcpt1oqKoUcE+XlJPdD+H+m2gUoAlWcgzzESG+euLOOUZq00RtZk="
